---
all:
    vars:
      ansible_user: root
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    children:
        loumaris-cloud:
          hosts:
              my.new.host.in.loumaris.cloud
                ansible_host: 1.2.3.4
